### ISSUE TITLE
Hide lang switch depends on current page

### ISSUE THREAD

**Issue by soylent-grin** [uchku/portfolio#3]
Now on bot eng and ru pages you have links to eng and ru versions. Hide link to eng wersion on eng page and backwards.

**Comment by uchku** [comment]
It was fixed. Now pages have link as 'ru/index.html' and 'en/index.html'. Did you check it?

**Comment by uchku** [comment]
I fixed this bug. Also I fixed mobile version of page. Picture of language is not big in mobile version now. I collapse ico in mobile version.
