### ISSUE TITLE
Add a favico

### ISSUE THREAD

**Issue by soylent-grin** [uchku/portfolio#4]
Use a favico generator or draw it by yourself. Put it in the root of repository.

**Comment by chistyakov** [comment]
Check links from this issue: https://github.com/ailabitmo/foodpedia/issues/20
The Real Favicon Generator was particularly helpfull for me.

**Comment by soylent-grin** [comment]
Hi there @chistyakov! How goes it in Russian Armed Forces?

**Comment by chistyakov** [comment]
Привет! Отлично.
Тамада хороший, конкурсы интересные.

**Comment by uchku** [comment]
I have added favicon for all pages of portfolio. Please check it.
