### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by soylent-grin** [uchku/portfolio#5]
Its a good tone to create a readme for every public repo (even if it just a portfolio). Just put a description of what this code is for. Try some Markdown synax when writing it.

**Comment by uchku** [comment]
I added simple Readme for portfolio.

**Comment by soylent-grin** [comment]
Add it to `master` branch - if it is on `gh-pages` it is not visible for people, who followed the link https://github.com/uchku/portfolio

**Comment by uchku** [comment]
I have done it
